# Generated by Django 4.2.5 on 2023-10-16 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_product_image_remove_product_tags_delete_tag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
